import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { Web3Provider } from "../../wagmi";
import "./globals.css";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

// 🧭 Metadata untuk SEO dan tab info
export const metadata: Metadata = {
  title: "SNAP App",
  description: "Generated by create next app",
};

// 📱 Viewport setting untuk mobile scaling
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white-primary h-full w-full p-0 m-0">
      <body
        className={`${poppins.className} ${geistSans.variable} ${geistMono.variable} antialiased h-full w-full p-0 m-0`}
      >
        <Web3Provider>{children}</Web3Provider>
      </body>
    </html>
  );
}
